
package com.lingqie.jianwang;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.8
 * Wed Oct 19 12:21:50 CST 2016
 * Generated source version: 2.2.8
 * 
 */
 
public class SimpleService_P1_Server{

    protected SimpleService_P1_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new SimpleServiceImpl();
        String address = "http://localhost:8080/jianwang/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new SimpleService_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
