package com.lingqie.jianwang;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.8
 * Wed Oct 19 12:23:02 CST 2016
 * Generated source version: 2.2.8
 * 
 */
 
@WebService(targetNamespace = "http://lingqie.com/jianwang", name = "SimpleService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SimpleService {

    @WebResult(name = "concatResponse", targetNamespace = "http://lingqie.com/jianwang", partName = "parameters")
    @WebMethod(action = "http://lingqie.com/jianwang/NewOperation")
    public java.lang.String concat(
        @WebParam(partName = "parameters", name = "concatRequest", targetNamespace = "http://lingqie.com/jianwang")
        ConcatRequest parameters
    );
}
